# Generated by Django 2.0.7 on 2018-07-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('st_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clickevent', to='shortener.UrlDetails')),
            ],
        ),
    ]
