# Generated by Django 2.0.7 on 2018-07-29 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180729_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetails',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2018, 7, 29)),
        ),
        migrations.AlterField(
            model_name='urldetails',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
