# Generated by Django 2.0.7 on 2018-07-29 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20180729_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetails',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
