# Generated by Django 2.0.7 on 2018-07-29 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20180729_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urldetails',
            options={'verbose_name_plural': 'UrlDetails'},
        ),
        migrations.AlterField(
            model_name='urldetails',
            name='timestamp',
            field=models.DateField(default=datetime.date(2018, 7, 29)),
        ),
    ]
