# Generated by Django 2.0.7 on 2018-07-29 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20180729_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetails',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
