# Generated by Django 2.0.7 on 2018-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20180729_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetails',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
